apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  labels:
    app: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:                      # ← this spec is under template
      containers:              # ← must be nested here
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80


